apiVersion: v1
kind: Secret
metadata:
  name: {{ template "relay.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{- if .Values.relay.secrets.relayCogToken }}
  relay-cog-token: {{ .Values.relay.secrets.relayCogToken | b64enc | quote }}
  {{- else }}
  relay-cog-token: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.docker.registryPassword }}
  docker-registry-password: {{ .Values.docker.registryPassword | b64enc | quote }}
  {{- end }}
